server:
  port: 8081
  servlet:
    context-path: /wechat

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my-wedding
    username: root
    password: p0o9i8u7
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

logging:
  config: classpath:logback.xml
